### ISSUE TITLE
Air Quality sensor wont show in HomeKit

### ISSUE THREAD

**Issue by abdelaziz13** [iprak/winix#10]
Air Quality sensor wont show in HomeKit, I am noob to HomeAssistant and I did everything as you said, I can see my Winix air purifiers on HomeKit showing as fans, however the air quality dont show. I would really appreciate your help. Thanks.

**Comment by iprak** [comment]
I think you are referring to the [HomeKit integration](https://www.home-assistant.io/integrations/homekit/) which supports AirQualitySensor. The data provided by Winix does not have any air quality sensor metrics, what it provides is a calculate QValue and air quality status of "good,fair,poor" and so the sensor exposed is not based on AirQualitySensor.

**Comment by abdelaziz13** [comment]
The good, fair and poor those are for AirQualitySensor. If you check the winix app the Air Quality only shows fair, poor or good, and homebridge addon also expose the air quality sensor in HomeKit and the values are fair, poor or good. I’m new to all this, I was just wondering why homebridge does show the air quality but this one on home assistant doesn’t. Thanks again.

**Comment by iprak** [comment]
It might be because the Winix sensor is not [AirQualitySensor ](https://github.com/home-assistant/core/blob/ac3a6aaa8cdb005b3c900f9d9671e5a859351060/homeassistant/components/air_quality/__init__.py) sensor, there is no particle matter data exposed by Winix purifier. The Winix qValue sensor just exposed the air_qvalue value exposed by Winix end point.

**Comment by iprak** [comment]
Closing this since the data exposed by Winix framework does not provide creation of an AirQualitySensor.
